let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Smart Tvs",
    price: 45000,
    desc: "Best resolution power and high internet connectivity.",
    img: "images/smarttv.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Iphones",
    price: 91200,
    desc: "The class you belong...",
    img: "images/iphones.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Laptops",
    price: 25999,
    desc: "Nice in programming.",
    img: "images/laptops.jpg",
  },
  {
    id: "thyfhcbcv",
    name:"Refrigerators",
    price: 30000,
    desc: "Stay fresh 365 days.",
    img: "images/fridges.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Printers",
    price: 13460,
    desc: "Save power and fast in printing.",
    img: "images/printers.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "BT Hoofers",
    price: 9000,
    desc: "Scare the neighbours.",
    img: "images/hoofers.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Android phones",
    price: 17599,
    desc: "Developed by google.",
    img: "images/phone.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Macbooks",
    price: 110000,
    desc: "Apple product good in coding.",
    img: "images/images.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Desktops",
    price: 13500,
    desc: "Best one it solve office work more effectively.",
    img: "images/desktop.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "External hard drives",
    price: 4999,
    desc: "No need for cloud computing .",
    img: "images/harddisk.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Microwaves",
    price: 6790,
    desc: "Save power and one year warranty.",
    img: "images/microwave.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Projectors",
    price: 25199,
    desc: "Best resolution ever suit for all eyes defects.",
    img: "images/projectors.jpg",
  },
];
